### PR TITLE
Remove the unnecessary folder

### PR DESCRIPTION
**Pull request by Eeshu-Yadav**
remove the unnecessary folder and make them in deployment ready state , suitable for making docker-container

### CODE REVIEW

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry merge it

**Comment by ivedantmistry** [comment]
@VictorAO-django can you please review this pr?

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry 
Screenshot 2024-10-07 183533
this is the well formatted repo , with docker-container also. and i have only remove the unnecessary and nothing else , there is no conflict with the base branch also.

**Comment by VictorAO-django** [comment]
@Eeshu-Yadav is this the screenshot you intended to send?

**Comment by Eeshu-Yadav** [comment]
@VictorAO-django review this pr , i have to merge it.

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry also add the label of hacktober fest.

**Pull request merged**
