### PR TITLE
Hide SECRET_KEY using environment variables

### PR DESCRIPTION
**Pull request by kavyachouhan**
This PR resolves the issue of exposing the SECRET_KEY in the settings.py file by loading the key from environment variables using python-decouple. I've also added .env to .gitignore to prevent future exposures.

This PR resolves issue #5 

image

### CODE REVIEW

**Review by VictorAO-django — APPROVED** [review]
Good thing hiding the secret key

**Review by VictorAO-django — APPROVED** [review]
It has no conflict with the existing branch..
It's ready for merging

**Comment by ivedantmistry** [comment]
@kavyachouhan please raise PR again as I merged last PR this request has conflicts.

**Comment by kavyachouhan** [comment]
@ivedantmistry I updated the code with new merges. This branch has no conflicts now.

**Pull request merged**
