### PR TITLE
Auth Feature

### PR DESCRIPTION
**Pull request by VictorAO-django**
I've been able to:

1. setup the Django project
2. Create the SignUp API Endpoint
3. Create the SignIn API Endpoint
4. Create the Email verification API Endpoint
5. Built and configure the OTP system which will be in use across all aspect of the project
6. Implement JWT authentication feature

### CODE REVIEW

**Comment by ivedantmistry** [comment]
@VictorAO-django can you please create new branch?

**Comment by VictorAO-django** [comment]
@ivedantmistry I created a new branched named 'auth' on my forked repository prior to creating the Pull request, not on the main/master branch

**Comment by ivedantmistry** [comment]
@VictorAO-django how to check if this works?

**Comment by VictorAO-django** [comment]
@ivedantmistry 
I'll be writing test cases soon
I made a pull request without it in other not to be a blocker for other contributors, as I am expected to start the project

**Comment by ivedantmistry** [comment]
@VictorAO-django okay

**Comment by VictorAO-django** [comment]
@ivedantmistry 
I made a pull request for a new branch which contains the test cases

**Pull request merged**
